version: "3.6"

services:
  base: &base
    build:
      context: ../
      dockerfile: .buildkite/Dockerfile
      args:
        - RUBY_IMAGE
    environment:
      CI:
      MEMCACHE_SERVERS: "memcached:11211"
      MYSQL_HOST: "${MYSQL_SERVICE-mysql}"
      PGHOST: postgres
      PGUSER: postgres
      QC_DATABASE_URL: "postgres://postgres@postgres/active_jobs_qc_int_test"
      QUE_DATABASE_URL: "postgres://postgres@postgres/active_jobs_que_int_test"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
      REDIS_URL: "redis://redis:6379/1"

  default: &default
    <<: *base
    depends_on:
      - memcached
      - redis
      - "${MYSQL_SERVICE-mysql}"
      - postgres

  activejob:
    <<: *default
    depends_on:
      - memcached
      - redis
      - "${MYSQL_SERVICE-mysql}"
      - postgres
      - rabbitmq
      - beanstalkd

  memcached:
    image: memcached:alpine

  redis:
    image: redis:alpine

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  postgres:
    image: postgres:alpine

  rabbitmq:
    image: rabbitmq:alpine

  beanstalkd:
    build:
      context: ./
      dockerfile: Dockerfile.beanstalkd
