version: "3.6"

services:
  default: &default
    image: "${IMAGE_NAME?}"
    environment:
      CI:
      BUILDKITE_PARALLEL_JOB:
      BUILDKITE_PARALLEL_JOB_COUNT:

      # Sauce Labs username and access key. Obfuscated, purposefully not encrypted.
      ENCODED: "U0FVQ0VfQUNDRVNTX0tFWT1hMDM1MzQzZi1lOTIyLTQwYjMtYWEzYy0wNmIzZWE2MzVjNDggU0FVQ0VfVVNFUk5BTUU9cnVieW9ucmFpbHM="

      BEANSTALK_URL: "beanstalk://beanstalkd"
      MEMCACHE_SERVERS: "memcached:11211"
      MYSQL_HOST: "${MYSQL_SERVICE-mysql}"
      PGHOST: postgres
      PGUSER: postgres
      QC_DATABASE_URL: "postgres://postgres@postgres/active_jobs_qc_int_test"
      QUE_DATABASE_URL: "postgres://postgres@postgres/active_jobs_que_int_test"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
      REDIS_URL: "redis://redis:6379/1"
      SELENIUM_DRIVER_URL: "http://chrome:4444/wd/hub"
    depends_on:
      - redis
      - memcached
      - "${MYSQL_SERVICE-mysql}"
      - postgres
    entrypoint:
      - await
      - tcp://redis:6379
      - tcp://memcached:11211
      - tcp://${MYSQL_SERVICE-mysql}:3306
      - postgres://postgres@postgres:5432/postgres
      - --

  activejob:
    <<: *default
    depends_on:
      - redis
      - memcached
      - "${MYSQL_SERVICE-mysql}"
      - postgres
      - rabbitmq
      - beanstalkd

  actionview:
    <<: *default
    depends_on:
      - redis
      - memcached
      - "${MYSQL_SERVICE-mysql}"
      - postgres
      - chrome
    entrypoint:
      - await
      - tcp://redis:6379
      - tcp://memcached:11211
      - tcp://${MYSQL_SERVICE-mysql}:3306
      - postgres://postgres@postgres:5432/postgres
      - tcp://chrome:4444
      - --

  memcached:
    image: memcached:alpine

  redis:
    image: redis:alpine

  mysql: &mysql
    image: mysql:latest
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "./mysql-initdb.d:/docker-entrypoint-initdb.d"

  mariadb:
    <<: *mysql
    image: mariadb:latest

  postgres:
    image: postgres:alpine

  rabbitmq:
    image: rabbitmq:alpine

  beanstalkd:
    build:
      context: ./
      dockerfile: Dockerfile.beanstalkd

  chrome:
    image: selenium/standalone-chrome:latest
