version: "3.6"

services:
  base:
    build: &build
      context: ../
      dockerfile: .buildkite/Dockerfile
      args:
        - RUBY_IMAGE

  default: &default
    image: "${IMAGE_NAME-buildkite_base}"
    environment:
      CI:
      BUILDKITE_PARALLEL_JOB:
      BUILDKITE_PARALLEL_JOB_COUNT:
      BEANSTALK_URL: "beanstalk://beanstalkd"
      MEMCACHE_SERVERS: "memcached:11211"
      MYSQL_HOST: "${MYSQL_SERVICE-mysql}"
      PGHOST: postgres
      PGUSER: postgres
      QC_DATABASE_URL: "postgres://postgres@postgres/active_jobs_qc_int_test"
      QUE_DATABASE_URL: "postgres://postgres@postgres/active_jobs_que_int_test"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
      REDIS_URL: "redis://redis:6379/1"
    depends_on:
      - memcached
      - redis
      - "${MYSQL_SERVICE-mysql}"
      - postgres
    entrypoint: "await postgres://postgres@postgres:5432/postgres tcp://redis:6379 tcp://memcached:11211 tcp://${MYSQL_SERVICE-mysql}:3306 --"

  activejob:
    <<: *default
    depends_on:
      - memcached
      - redis
      - "${MYSQL_SERVICE-mysql}"
      - postgres
      - rabbitmq
      - beanstalkd

  memcached:
    image: memcached:alpine

  redis:
    image: redis:alpine

  mysql: &mysql
    image: mysql:latest
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "./mysql-initdb.d:/docker-entrypoint-initdb.d"

  mariadb:
    <<: *mysql
    image: mariadb:latest

  postgres:
    image: postgres:alpine

  rabbitmq:
    image: rabbitmq:alpine

  beanstalkd:
    build:
      context: ./
      dockerfile: Dockerfile.beanstalkd
