#!/bin/bash

set -e

echo "--- :docker: Building docker image with buildkit"

export RUBY_IMAGE="$1"

REPOSITORY="973266071021.dkr.ecr.us-east-1.amazonaws.com/builds"
TAG="$(echo "$RUBY_IMAGE" | tr ':' '-')-${BUILDKITE_BUILD_ID}"

DOCKER_BUILDKIT=1 docker build --build-arg RUBY_IMAGE -f .buildkite/Dockerfile -t "$REPOSITORY:$TAG" --progress=plain .

echo "--- :docker: Pushing docker image"

docker push "$REPOSITORY:$TAG"

#echo "--- :buildkite: Setting meta-data for docker-compose plugin"

#buildkite-agent meta-data set "docker-compose-plugin-built-image-tag-default-.buildkite/docker-compose.yml" "$REPOSITORY:$TAG"
